# -*- coding: utf-8 -*-
"""Step-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z8amFBDqs0kos17_bOBLJPjuFUa4f9RW
"""

import requests

   

getUrl = 'https://todn22mvx9.execute-api.ap-south-1.amazonaws.com/dev/screeningForm?email=tithi888khan@gmail.com'


#use the 'headers' parameter to set the HTTP headers:
getResponse = requests.get(getUrl, headers = {"accesstoken": "zIWZKnAk4OYbYzbc-tithi888khan%40gmail.com-Y85fY4DozgOgfsgi", "x-api-key": "JU9eKYSwUW6lVlvGKrUkF71P1aybSR9y73jZ00y0"})

print(getResponse.text)

#the 'demopage.asp' prints all HTTP Headers

"""{"instructions":"Impressive! Kudos to you that you are in this step. With this response, you have a stringified array of strings as part of urlObject property. As part of this step you need to find the actual URL from the urlObject. \n             Now you must be wondering how you will find that? We will now tell you how we actually created this urlObject so that you can do reverse engineering to get it back. On the very first step, we encoded the actual URL using base64 encoding. Then we split the base64 encoded URL for every 50 characters \n             to get an array of strings. Then we have randomly shuffled the array so the orders become random. Then we have stringified the array of strings and sent you as part of urlObject property.\n             Now please try to find out the correct URL. Don't try to find it manually and rather write a code in your favorite language to find it easily. \n             Once you have found the correct URL, paste it into a browser and from there you will get the next instruction :-)\n             All the best!","urlObject":"[\"b2xHcGxablNvLUw2akFBL3ZpZXdmb3JtP3VzcD1wcF91cmwmZW\",\"50cnkuMTk1NDA1MDMwND10aXRoaTg4OGtoYW5AZ21haWwuY29t\",\"50cnkuMTAxMzkwOTE1PXpJV1pLbkFrNE9ZYll6YmMtdGl0aGk4\",\"lwUUxTZS1nQUx1eFBKanJPVEZ2MnpCX0FSQVFBbEtGRHlYdTVS\",\"ODhraGFuJTQwZ21haWwuY29tLVk4NWZZNERvemdPZ2ZzZ2kmZW\",\"aHR0cHM6Ly9kb2NzLmdvb2dsZS5jb20vZm9ybXMvZC9lLzFGQU\"]"}"""

import base64
def base64ToString(b):
    return base64.b64decode(b).decode('utf-8')

urlData = ["b2xHcGxablNvLUw2akFBL3ZpZXdmb3JtP3VzcD1wcF91cmwmZW","50cnkuMTk1NDA1MDMwND10aXRoaTg4OGtoYW5AZ21haWwuY29t","50cnkuMTAxMzkwOTE1PXpJV1pLbkFrNE9ZYll6YmMtdGl0aGk4","lwUUxTZS1nQUx1eFBKanJPVEZ2MnpCX0FSQVFBbEtGRHlYdTVS","ODhraGFuJTQwZ21haWwuY29tLVk4NWZZNERvemdPZ2ZzZ2kmZW","aHR0cHM6Ly9kb2NzLmdvb2dsZS5jb20vZm9ybXMvZC9lLzFGQU"]

print(urlData)

import itertools
# list(itertools.permutations(urlData))
for permutation in itertools.permutations(urlData):
  # print(permutation)
  # print("-------------------------------------------")
  combinedBase64 = "".join(permutation)
  # print(combinedBase64)
  try: 
    decoded = base64ToString(combinedBase64)
    print(decoded)
    print("-----------------------------------")
  except:
    pass

for